##deployement
#spring:
#  config:
#    import: optional:configserver:http://config-server:8888
#  application:
#    name: gateway-service

#local
spring:
  config:
    import: configserver:http://localhost:8888
  application:
    name: gateway-service